version: '3.3'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    port:
      - 8050:8080
      - 50000:50000
    volumes:
      - ./data/jenkins:/var/jenkins_home